DL: Update ind/dep var shape to INTEGER instead of smallint
JIRA: MADLIB-1468

training_preprocessor_dl() function fails with the following error when the
number of images in a buffer is > range for smallint i.e. -32768 to +32767.
```
ERROR: spiexceptions.NumericValueOutOfRange: smallint out of range
```
This commit replaces smallint with INTEGER for the shape column.

Co-authored-by: Nikhil Kak <nkak@vmware.com>