DL: Update jenkins to install tensorflow 1.14.
The latest version of tensorflow (2.0 as of this commit) is not compatible with the version of keras that we install i.e. 2.2.4.

This is the error we get
```
AttributeError: 'module' object has no attribute 'get_default_graph'
```

This commit installs a compatible version of tensorflow i.e. 1.14.