DL: Remove keras dependency
JIRA: MADLIB-1438

Remove keras dependency to use the keras from the tensorflow package.
Also, removed the channels first test since it only works on GPUs. It
fails on a the CPU for the following error:
```
ERROR: spiexceptions.ExternalRoutineException:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default
MaxPoolingOp only supports NHWC on device type CPU
```

In order for MaxPooling to work on a channel-first dataset with CPU's,
we need a version of tensorflow that supports MKL(Intel Math Kernel
Library).  Since this is an edge case, we are removing the channels
first tests.